### ISSUE TITLE
Optimization: strlen has been called more than once over same string

### ISSUE THREAD

**Issue by 0xTheProDev** [BytesClub/serverX#1]
Link: 
* https://github.com/BytesClub/serverX/blob/master/src/serverXL.c#L890
* https://github.com/BytesClub/serverX/blob/master/src/serverXL.c#L898

**Comment by krhitesh** [comment]
Instead of:
`char* t = calloc(strlen(s) + 1, 1);    //Line 890`
use:
`int s_len;`

`char* t = calloc(s_len=strlen(s) + 1, 1);`
Use `s_len` in Line 898 too instead of `strlen(s)`.

**Comment by 0xTheProDev** [comment]
@hitesh1157 Thanks for your suggestion. You may look into this issue and send us pull request when you're done. In the meantime, we will like you to go through our **[Contribution Guide](https://bytesclub.github.io/contributing/)** and **[Coding Style](https://bytesclub.github.io/docs/coding_style.pdf)**.
