### ISSUE TITLE
Thread: The server should be able to handle multiple requests at the same time

### ISSUE THREAD

**Issue by rubencm** [BytesClub/serverX#14]

**Comment by 0xTheProDev** [comment]
@rubencm Please follow #9

**Comment by rubencm** [comment]
@Progyan1997 Is not the same (but will be part of it)

**Comment by Progyan1997** [comment]
Contribute under #9 , no need for sep

**Comment by rubencm** [comment]
With this i mean multiple requests from the same/diferent users.
To solve your issue i still have to do a lot of things (like supporting keep-alive)
